services:
  frontend:
    container_name: onlineshop_frontend
    build: ../frontend
    depends_on:
      - web
    networks:
      - onlineshop-network
  web:
    container_name: onlineshop_web
    build: .
    image: onlineshop:latest
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=*
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - onlineshop-network

  celery:
    container_name: onlineshop_celery
    image: onlineshop:latest
    working_dir: /app
    command: celery -A core.celery_config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    networks:
      - onlineshop-network

  redis:
    container_name: onlineshop_redis
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - onlineshop-network

networks:
  onlineshop-network:
    driver: bridge

volumes:
  media_volume: